api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView)

from .views import (
    CustomUserViewSet,
    BluRayViewSet,
    MovieViewSet,
    MovieDirectorViewSet,
    MovieActorViewSet,
    PeopleViewSet,
    DealViewSet,
    FavoriteBluRayViewSet,
    FavoriteMovieViewSet,
    FavoritePeopleViewSet,
    BluRayRequestViewSet,
    MovieRequestViewSet,
    PeopleRequestViewSet,
    DealRequestViewSet)

app_name = "api"

router = DefaultRouter()
router.APIRootView.__name__ = "Bloodeal"
router.APIRootView.__doc__ = "API de l'application Bloodeal"
router.register(r'users', CustomUserViewSet)
router.register(r'blurays', BluRayViewSet)
router.register(r'movies', MovieViewSet, basename="movies")
router.register(r'movies_directors', MovieDirectorViewSet)
router.register(r'movies_actors', MovieActorViewSet)
router.register(r'people', PeopleViewSet)
router.register(r'deals', DealViewSet)
router.register(r'favorite_blurays', FavoriteBluRayViewSet)
router.register(r'favorite_movies', FavoriteMovieViewSet)
router.register(r'favorite_people', FavoritePeopleViewSet)
router.register(r'bluray_requests', BluRayRequestViewSet)
router.register(r'movie_requests', MovieRequestViewSet)
router.register(r'people_requests', PeopleRequestViewSet)
router.register(r'deal_requests', DealRequestViewSet)

urlpatterns = [
    path('login/', TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path('login/refresh/', TokenRefreshView.as_view(), name="token_refresh"),
    path('v1/', include(router.urls)),
    path('v1/', router.APIRootView.as_view(), name="v1"),
]

bloodeal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from accounts.views import sentry_error, generate_pdf

favicon_view = RedirectView.as_view(url='/static/img/favicon.png',
                                    permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('', include("accounts.urls"), name="accounts"),
    path('profiles/', include("profiles.urls"), name="profiles"),
    path('blurays/', include("blurays.urls"), name="blurays"),
    path('deals/', include("deals.urls"), name="deals"),
    path('movies/', include("movies.urls"), name="movies"),
    path('people/', include("people.urls"), name="people"),
    path('requests/', include("user_requests.urls"), name="user_requests"),
    path('api/', include("api.urls"), name="api"),
    path('site-admin/', admin.site.urls),
    path('sentry-debug/', sentry_error, name="sentry"),
    path('pdf/', generate_pdf, name="pdf"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blurays/urls.py
from django.urls import path

from blurays.views import BluRayListView, BluRayDetailView

# Création d'un espace de noms
app_name = 'blurays'

urlpatterns = [path('list/', BluRayListView.as_view(), name="blurays_list"),
               path('<str:slug>/<int:pk>/', BluRayDetailView.as_view(), name="blurays_detail")]

deals/urls.py
from django.urls import path

from deals.views import DealListView, DealCreateView, DealDetailView

# Création d'un espace de noms
app_name = "deals"

urlpatterns = [path("list/", DealListView.as_view(), name="deals_list"),
               path("<int:pk>/", DealDetailView.as_view(), name="deals_detail"),
               path("create/", DealCreateView.as_view(), name="deals_create")]

movies/urls.py
from django.urls import path

from movies.views import MovieListView, MovieDetailView


# Création d'un espace de noms
app_name = 'movies'

urlpatterns = [path("list/", MovieListView.as_view(), name="movies_list"),
               path("<str:slug>/<int:pk>/", MovieDetailView.as_view(), name="movies_detail")]

people/urls.py
from django.urls import path

from .views import PeopleListView, PeopleDetailView


# Création d'un espace de noms
app_name = 'people'

urlpatterns = [path('list/', PeopleListView.as_view(), name='people_list'),
               path('<str:slug>/<int:pk>/', PeopleDetailView.as_view(), name='people_detail')]

user_requests/urls.py
from django.urls import path

from .views import (
    MovieRequestCreateView,
    BluRayRequestCreateView,
    PeopleRequestCreateView,
    UserRequestListView,
    DealRequestCreateView)

# Création d'un espace de noms
app_name = 'user_requests'

urlpatterns = [path('<int:pk>/',
                    UserRequestListView.as_view(),
                    name="user_requests"),
               path('add-a-bluray/',
                    BluRayRequestCreateView.as_view(),
                    name="bluray_request_create"),
               path('add-a-movie/',
                    MovieRequestCreateView.as_view(),
                    name="movie_request_create"),
               path('add-a-people/',
                    PeopleRequestCreateView.as_view(),
                    name="people_request_create"),
               path('add-a-deal/',
                    DealRequestCreateView.as_view(),
                    name="deal_request_create")]

user_requests/models.py
from itertools import chain

from django.conf import settings
from django.db import models
import re

from django.db.models import Value, CASCADE

from blurays.models import BluRay
from deals.models import Deal
from movies.models import Movie
from people.models import People
from .functions import IMDBMovieData, IMDBPeopleData

STATUS_CHOICES = [("1", "En-cours"),
                  ("2", "Acceptée"),
                  ("3", "Refusée"),
                  ("4", "Indéterminée")]


# Create your models here.
class PeopleRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=CASCADE,
                             related_name='people_user_request',
                             blank=False,
                             null=False)
    imdb_link = models.URLField(blank=False,
                                null=False,
                                verbose_name="Lien IMDB")
    imdb_id = models.CharField(max_length=9, blank=True, null=True)
    first_name = models.CharField(max_length=256,
                                  blank=True,
                                  null=True)
    last_name = models.CharField(max_length=256,
                                 blank=True,
                                 null=True)
    birth_date = models.DateField("Date de naissance",
                                  blank=True,
                                  null=True)
    death_date = models.DateField("Date de décès",
                                  blank=True,
                                  null=True)
    people = models.ForeignKey(People,
                               on_delete=CASCADE,
                               blank=True,
                               null=True)
    status = models.CharField(max_length=56,
                              choices=STATUS_CHOICES,
                              blank=False,
                              null=False,
                              default="1")
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Demande de personnalité N° {self.pk}"

    def get_imdb_id(self):
        imdb_id = re.search(r"nm[0-9].[^(?:/|?)]+", str(self.imdb_link))
        if imdb_id:
            imdb_id = imdb_id[0]
        return imdb_id

    def save(self, **kwargs):
        if self.imdb_link and not self.imdb_id:
            imdb_id = self.get_imdb_id()
            if imdb_id:
                self.imdb_id = imdb_id
                try:
                    people = IMDBPeopleData(imdb_id)
                    first_name = people.imdb_get_first_name
                    self.first_name = first_name if first_name else None
                    last_name = people.imdb_get_last_name
                    self.last_name = last_name if last_name else None
                    birth_date = people.imdb_get_birth_date
                    self.birth_date = birth_date if birth_date else None
                    death_date = people.imdb_get_death_date
                    self.death_date = death_date if death_date else None
                except (ConnectionError, ):
                    print(f"Impossible de scraper le site IMDB pour {imdb_id}")
        return super().save(**kwargs)

    class Meta:
        verbose_name = "Traité - Personnalité"
        verbose_name_plural = "Traité - Personnalités"


# Le filtre est fait via le manager au niveau du proxy model
class PeopleRequestManager(models.Manager):
    def get_queryset(self):
        return super(PeopleRequestManager, self).get_queryset().filter(status="1")


class PeopleRequestOpen(PeopleRequest):
    objects = PeopleRequestManager()

    class Meta:
        proxy = True
        verbose_name = "A traiter - Personnalité"
        verbose_name_plural = "A traiter - Personnalités"


class MovieRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=CASCADE,
                             related_name='movie_user_request',
                             blank=False,
                             null=False)
    imdb_link = models.URLField(blank=False,
                                null=False,
                                verbose_name="Lien IMDB")
    imdb_id = models.CharField(max_length=9, blank=True, null=True)
    title_vf = models.CharField(max_length=200,
                                blank=True,
                                null=True)
    title_vo = models.CharField(max_length=200,
                                blank=True,
                                null=True)
    release_year = models.IntegerField(blank=True,
                                       null=True)
    movie = models.ForeignKey(Movie,
                              on_delete=CASCADE,
                              blank=True,
                              null=True)
    status = models.CharField(max_length=56,
                              choices=STATUS_CHOICES,
                              blank=False,
                              null=False,
                              default="1")
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Demande de films N° {self.pk}"

    def get_imdb_id(self):
        imdb_id = re.search(r"tt[0-9].[^(?:/|?)]+", str(self.imdb_link))
        if imdb_id:
            imdb_id = imdb_id[0]
        return imdb_id

    def save(self, **kwargs):
        if self.imdb_link and not self.imdb_id:
            imdb_id = self.get_imdb_id()
            if imdb_id:
                self.imdb_id = imdb_id
                try:
                    movie = IMDBMovieData(imdb_id)
                    title_vf = movie.imdb_get_title
                    self.title_vf = title_vf if title_vf else None
                    self.title_vo = title_vf
                    release_year = movie.imdb_get_release_year
                    self.release_year = int(release_year) if release_year else None
                except (ConnectionError, ):
                    print(f"Impossible de scraper le site IMDB pour {imdb_id}")

        return super().save(**kwargs)

    class Meta:
        verbose_name = "Traité - Film"
        verbose_name_plural = "Traité - Films"


# Le filtre sera fait en surchagreant la méthode get_queryset au niveau du
# ModelAdmin
class MovieRequestOpen(MovieRequest):
    class Meta:
        proxy = True
        verbose_name = "A traiter - Film"
        verbose_name_plural = "A traiter - Films"


class BluRayRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=CASCADE,
                             related_name='bluray_user_request',
                             blank=False,
                             null=False)
    amazon_link = models.URLField(blank=False,
                                  null=False,
                                  verbose_name="Lien Amazon")
    asin = models.CharField(max_length=10,
                            blank=True,
                            null=True)
    bluray = models.ForeignKey(BluRay,
                               on_delete=CASCADE,
                               related_name='created_bluray',
                               blank=True,
                               null=True)
    status = models.CharField(max_length=56,
                              choices=STATUS_CHOICES,
                              blank=False,
                              null=False,
                              default="1")
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Demande de Blu-Ray N° {self.pk}"

    def get_asin(self):
        asin = re.search(r"B0[.]*[^(?:/|?)]+", str(self.amazon_link))
        if asin:
            asin = asin[0]
        return asin

    def save(self, **kwargs):
        if self.amazon_link and not self.asin:
            asin = self.get_asin()
            if asin:
                self.asin = asin
        return super().save(**kwargs)

    class Meta:
        verbose_name = "Traité - Blu-Ray"
        verbose_name_plural = "Traité - Blu-Rays"


class BluRayRequestOpen(BluRayRequest):
    class Meta:
        proxy = True
        verbose_name = "A traiter - Blu-Ray"
        verbose_name_plural = "A traiter - Blu-Rays"


class DealRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=CASCADE,
                             related_name='deal_user_request',
                             blank=False,
                             null=False)
    bluray = models.ForeignKey(BluRay,
                               on_delete=CASCADE,
                               blank=True,
                               null=True)
    amazon_link = models.URLField(blank=False,
                                  null=False,
                                  verbose_name="Lien Amazon")
    asin = models.CharField(max_length=10, blank=True, null=True)
    price = models.FloatField()
    deal = models.ForeignKey(Deal,
                             on_delete=CASCADE,
                             blank=True,
                             null=True)
    status = models.CharField(max_length=56,
                              choices=STATUS_CHOICES,
                              blank=False,
                              null=False,
                              default="1")
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Demande de bon plan N° {self.pk}"

    def get_asin(self):
        asin = re.search(r"B0[.]*[^(?:/|?)]+", str(self.amazon_link))
        if asin:
            asin = asin[0]
        return asin

    def save(self, **kwargs):
        if self.amazon_link and not self.asin:

user_requests/forms.py
from django.forms import ModelForm

from user_requests.models import BluRayRequest, MovieRequest, PeopleRequest


class BluRayCreationForm(ModelForm):
    class Meta:
        model = BluRayRequest
        fields = ["amazon_link", "user", "status"]


class MovieCreationForm(ModelForm):
    class Meta:
        model = MovieRequest
        fields = ["imdb_link", "user", "status"]


class PeopleCreationForm(ModelForm):
    class Meta:
        model = PeopleRequest
        fields = ["imdb_link", "user", "status"]


def generate_initialized_request_forms(user, status="1"):
    bluray_request_form = BluRayCreationForm(initial={"user": user,
                                                      "status": status},
                                             auto_id="bluray_request_%s")
    movie_request_form = MovieCreationForm(initial={"user": user,
                                                    "status": status},
                                           auto_id="movie_request_%s")
    people_creation_form = PeopleCreationForm(initial={"user": user,
                                                       "status": status},
                                              auto_id="people_request_%s")
    requests_forms = {"bluray_request_form": bluray_request_form,
                      "movie_request_form": movie_request_form,
                      "people_request_form": people_creation_form}
    return requests_forms

user_requests/templates/user_requests/add-a-bluray-snippet.html
<div class="dashboard-block-element min-height-20vh justify-content-center padding-1rem">
    {% if user.is_authenticated %}
    <h2>Suggérer un Blu-Ray</h2>
    <form method="post" action="{% url 'user_requests:bluray_request_create' %}">
        {% csrf_token %}
            {% for field in bluray_request_form %}
                    {% if forloop.counter >= 2 %}{{ field.as_hidden }}{% else %}
                    <div class="capsule">
                        <div class="capsule-text width-100">
                        <p>{{ field.label_tag }}</p>
                        <p>{{ field }}</p>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="errorlist">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            {% if messages %}
                                {% for message in messages %}
                                    {% if message.level != DEFAULT_MESSAGE_LEVELS.INFO %}
                                        <p class="errorlist">{{ message }}</p>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    {% endif %}
            {% endfor %}
        <button type="submit" name="bluray_request_form" class="btn btn-submit">J'envoie ma suggestion</button>
    </form>
    {% else %}
    <div class="capsule-text width-100">
        <p class="text-align-center margin-1rem">Connectez-vous pour suggérer un blu-ray.</p>
    </div>
    {% endif %}
</div>

user_requests/templates/user_requests/add-a-movie-snippet.html
<div class="dashboard-block-element min-height-20vh justify-content-center padding-1rem">
    {% if user.is_authenticated %}
    <h2>Suggérer un film</h2>
    <form method="post" action="{% url 'user_requests:movie_request_create' %}">
        {% csrf_token %}
            {% for field in movie_request_form %}
                    {% if forloop.counter >= 2 %}{{ field.as_hidden }}{% else %}
                    <div class="capsule">
                        <div class="capsule-text width-100">
                        <p>{{ field.label_tag }}</p>
                        <p>{{ field }}</p>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="errorlist">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            {% if messages %}
                                {% for message in messages %}
                                    {% if message.level != DEFAULT_MESSAGE_LEVELS.INFO %}
                                        <p class="errorlist">{{ message }}</p>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    {% endif %}
            {% endfor %}
        <button type="submit" name="form" class="btn btn-submit">J'envoie ma suggestion</button>
    </form>
    {% else %}
    <div class="capsule-text width-100">
        <p class="text-align-center margin-1rem">Connectez-vous pour suggérer un film.</p>
    </div>
    {% endif %}
</div>

user_requests/templates/user_requests/list-main-block.html
{% load static %}

<section class="dashboard-block main-block-min-width">
    <ul>
        <a class="margin-1rem" href="{% url 'user_requests:user_requests' pk=request.user.pk %}?filter=1+2+3+4">
            <li >Toutes vos demandes</li>
        </a>
        <a class="margin-1rem" href="{% url 'user_requests:user_requests' pk=request.user.pk %}?filter=1">
            <li>Seulement les demandes en-cours</li>
        </a>
        <a class="margin-1rem" href="{% url 'user_requests:user_requests' pk=request.user.pk %}?filter=2">
            <li>Seulement les demandes acceptées</li>
        </a>
        <a class="margin-1rem" href="{% url 'user_requests:user_requests' pk=request.user.pk %}?filter=3">
            <li>Seulement les demandes refusées</li>
        </a>
    </ul>
    <div class="dashboard-block-element padding-1rem">
        {% if user_requests_deals %}
        <div class="dashboard-block-element-title">
            <h2>VOS DEMANDES D'AJOUTS DE BONS PLANS ({{ user_requests_deals|length }})</h2>
        </div>
         <div class="dashboard-block-element-content justify-content-center flex-wrap">
            {% for request in user_requests_deals %}
                {% if request.deal %}
                    <div class="capsule justify-content-center width-100 {% cycle '' 'background-grey' %}">
                        <div class="capsule-text width-100">
                            <ul class="justify-content-center">
                                <li class="requests-list">
                                    {% if request.deal.pk %}
                                    Votre bon plan pour
                                    <a href="{% url 'deals:deals_detail' pk=request.deal.pk %}">
                                    {% endif %}
                                        <h2>{{ request.deal.bluray }}</h2>
                                    </a> a bien été enregistré suite à votre demande du {{ request.date_created|date:"d/m/Y" }}.
                                </li>
                            </ul>
                        </div>
                    </div>
                {% else %}
                    <div class="capsule justify-content-center width-100 {% cycle '' 'background-grey' %}">
                        <div class="capsule-text width-100">
                            <ul class="justify-content-center">
                                <li class="requests-list">Votre proposition de bon plan du {{ request.date_created|date:"d/m/Y" }} a le statut
                                    <span class="margin-1rem cursor-default btn {% if request.status == '1' %}btn-submit{% endif %}{% if request.status == '2' %}btn-validated{% endif %}{% if request.status == '3' %}btn-delete{% endif %}{% if request.status == '4' %}btn-unknown{% endif %}">
                                        {{ request.get_status_display }}
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <div class="capsule justify-content-center margin-auto">
            <h2>Aucune demande de bon plan trouvée.</h2>
        </div>
        {% endif %}
    </div>

    <div class="dashboard-block-element padding-1rem">
        {% if user_requests_blurays %}
        <div class="dashboard-block-element-title">
            <h2>VOS DEMANDES D'AJOUTS DE BLU-RAYS ({{ user_requests_blurays|length }})</h2>
        </div>
        <div class="dashboard-block-element-content justify-content-center flex-wrap">
            {% for request in user_requests_blurays %}
                {% if request.bluray %}
                    <div class="capsule justify-content-center width-100 {% cycle '' 'background-grey' %}">
                        <div class="capsule-text width-100">
                            <ul class="justify-content-center">
                                <li class="requests-list">
                                    {% if request.bluray.slug %}
                                    <a href="{% url 'blurays:blurays_detail' slug=request.bluray.slug pk=request.bluray.pk %}">
                                    {% endif %}
                                        <h2>{{ request.bluray }}</h2>
                                    </a> a bien été enregistré suite à votre demande du {{ request.date_created|date:"d/m/Y" }}.
                                </li>
                            </ul>
                        </div>
                    </div>
                {% else %}
                    <div class="capsule justify-content-center width-100 {% cycle '' 'background-grey' %}">
                        <div class="capsule-text width-100">
                            <ul class="justify-content-center">
                                <li class="requests-list">Votre demande d'ajout du {{ request.date_created|date:"d/m/Y" }} pour le blu-ray ayant l'identifiant Amazon
                                    <a href="{{ request.amazon_link }}" target="_blank"><span>{{ request.asin }}</span></a>a le statut
                                    <span class="margin-1rem cursor-default btn {% if request.status == '1' %}btn-submit{% endif %}{% if request.status == '2' %}btn-validated{% endif %}{% if request.status == '3' %}btn-delete{% endif %}{% if request.status == '4' %}btn-unknown{% endif %}">
                                        {{ request.get_status_display }}
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <div class="capsule justify-content-center margin-auto">
            <h2>Aucune demande de blu-ray trouvée.</h2>
        </div>
        {% endif %}
    </div>

    <div class="dashboard-block-element padding-1rem">
    {% if user_requests_movies %}
        <div class="dashboard-block-element-title">
            <h2>VOS DEMANDES D'AJOUTS DE FILMS ({{ user_requests_movies|length }})</h2>
        </div>
        <div class="dashboard-block-element-content justify-content-center flex-wrap">
            {% for request in user_requests_movies %}
                {% if request.movie %}
                    <div class="capsule justify-content-center width-100 {% cycle '' 'background-grey' %}">
                        <div class="capsule-text width-100">
                            <ul class="justify-content-center">
                                <li class="requests-list">
                                    {% if request.movie.slug %}
                                    <a href="{% url 'movies:movies_detail' slug=request.movie.slug pk=request.movie.pk %}">
                                    {% endif %}
                                        <h2>{{ request.movie }}</h2>
                                    </a> a bien été enregistré suite à votre demande du {{ request.date_created|date:"d/m/Y" }}.
                                </li>
                            </ul>
                        </div>
                    </div>
                {% else %}
                    <div class="capsule justify-content-center width-100 {% cycle '' 'background-grey' %}">
                        <div class="capsule-text width-100">
                            <ul class="justify-content-center">
                                <li class="requests-list">Votre demande d'ajout du {{ request.date_created|date:"d/m/Y" }} pour le film ayant l'identifiant IMDB
                                    <a href="{{ request.imdb_link }}" target="_blank"><span>{{ request.imdb_id }}</span></a>le statut
                                    <span class="margin-1rem cursor-default btn {% if request.status == '1' %}btn-submit{% endif %}{% if request.status == '2' %}btn-validated{% endif %}{% if request.status == '3' %}btn-delete{% endif %}{% if request.status == '4' %}btn-unknown{% endif %}">
                                        {{ request.get_status_display }}
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <div class="capsule justify-content-center margin-auto">
            <h2>Aucune demande de film trouvée.</h2>
        </div>
        {% endif %}
    </div>

    <div class="dashboard-block-element padding-1rem">
        {% if user_requests_people %}
        <div class="dashboard-block-element-title">
            <h2>VOS DEMANDES D'AJOUTS DE PERSONNALITES ({{ user_requests_people|length }})</h2>
        </div>
        <div class="dashboard-block-element-content justify-content-center flex-wrap">
            {% for request in user_requests_people %}
                {% if request.people %}
                    <div class="capsule justify-content-center width-100 {% cycle '' 'background-grey' %}">
                        <div class="capsule-text width-100">
                            <ul class="justify-content-center">
                                <li class="requests-list">
                                    {% if request.people.slug %}
                                    <a href="{% url 'people:people_detail' slug=request.people.slug pk=request.people.pk %}">
                                    {% endif %}
                                        <h2>{{ request.people }}</h2>
                                    </a> a bien été enregistré suite à votre demande du {{ request.date_created|date:"d/m/Y" }}.
                                </li>
                            </ul>
                        </div>
                    </div>
                {% else %}
                    <div class="capsule justify-content-center width-100 {% cycle '' 'background-grey' %}">
                        <div class="capsule-text width-100">
                            <ul class="justify-content-center">
                                <li class="requests-list">
                                    <span>
                                        Votre demande d'ajout du {{ request.date_created|date:"d/m/Y" }} pour la personnalité ayant l'identifiant IMDB
                                        <a href="{{ request.imdb_link }}" target="_blank"><b>{{ request.imdb_id }}</b></a> a le statut
                                    </span>
                                    <span class="margin-1rem cursor-default btn {% if request.status == '1' %}btn-submit{% endif %}{% if request.status == '2' %}btn-validated{% endif %}{% if request.status == '3' %}btn-delete{% endif %}{% if request.status == '4' %}btn-unknown{% endif %}">
                                        {{ request.get_status_display }}
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <div class="capsule justify-content-center margin-auto">
            <h2>Aucune demande de personnalité trouvée.</h2>
        </div>
        {% endif %}
    </div>

</section>