api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView)

from .views import (
    CustomUserViewSet,
    BluRayViewSet,
    MovieViewSet,
    MovieDirectorViewSet,
    MovieActorViewSet,
    PeopleViewSet,
    DealViewSet,
    FavoriteBluRayViewSet,
    FavoriteMovieViewSet,
    FavoritePeopleViewSet,
    BluRayRequestViewSet,
    MovieRequestViewSet,
    PeopleRequestViewSet,
    DealRequestViewSet)

app_name = "api"

router = DefaultRouter()
router.APIRootView.__name__ = "Bloodeal"
router.APIRootView.__doc__ = "API de l'application Bloodeal"
router.register(r'users', CustomUserViewSet)
router.register(r'blurays', BluRayViewSet)
router.register(r'movies', MovieViewSet, basename="movies")
router.register(r'movies_directors', MovieDirectorViewSet)
router.register(r'movies_actors', MovieActorViewSet)
router.register(r'people', PeopleViewSet)
router.register(r'deals', DealViewSet)
router.register(r'favorite_blurays', FavoriteBluRayViewSet)
router.register(r'favorite_movies', FavoriteMovieViewSet)
router.register(r'favorite_people', FavoritePeopleViewSet)
router.register(r'bluray_requests', BluRayRequestViewSet)
router.register(r'movie_requests', MovieRequestViewSet)
router.register(r'people_requests', PeopleRequestViewSet)
router.register(r'deal_requests', DealRequestViewSet)

urlpatterns = [
    path('login/', TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path('login/refresh/', TokenRefreshView.as_view(), name="token_refresh"),
    path('v1/', include(router.urls)),
    path('v1/', router.APIRootView.as_view(), name="v1"),
]

bloodeal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from accounts.views import sentry_error, generate_pdf

favicon_view = RedirectView.as_view(url='/static/img/favicon.png',
                                    permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('', include("accounts.urls"), name="accounts"),
    path('profiles/', include("profiles.urls"), name="profiles"),
    path('blurays/', include("blurays.urls"), name="blurays"),
    path('deals/', include("deals.urls"), name="deals"),
    path('movies/', include("movies.urls"), name="movies"),
    path('people/', include("people.urls"), name="people"),
    path('requests/', include("user_requests.urls"), name="user_requests"),
    path('api/', include("api.urls"), name="api"),
    path('site-admin/', admin.site.urls),
    path('sentry-debug/', sentry_error, name="sentry"),
    path('pdf/', generate_pdf, name="pdf"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blurays/urls.py
from django.urls import path

from blurays.views import BluRayListView, BluRayDetailView

# Création d'un espace de noms
app_name = 'blurays'

urlpatterns = [path('list/', BluRayListView.as_view(), name="blurays_list"),
               path('<str:slug>/<int:pk>/', BluRayDetailView.as_view(), name="blurays_detail")]

deals/urls.py
from django.urls import path

from deals.views import DealListView, DealCreateView, DealDetailView

# Création d'un espace de noms
app_name = "deals"

urlpatterns = [path("list/", DealListView.as_view(), name="deals_list"),
               path("<int:pk>/", DealDetailView.as_view(), name="deals_detail"),
               path("create/", DealCreateView.as_view(), name="deals_create")]

movies/urls.py
from django.urls import path

from movies.views import MovieListView, MovieDetailView


# Création d'un espace de noms
app_name = 'movies'

urlpatterns = [path("list/", MovieListView.as_view(), name="movies_list"),
               path("<str:slug>/<int:pk>/", MovieDetailView.as_view(), name="movies_detail")]

people/urls.py
from django.urls import path

from .views import PeopleListView, PeopleDetailView


# Création d'un espace de noms
app_name = 'people'

urlpatterns = [path('list/', PeopleListView.as_view(), name='people_list'),
               path('<str:slug>/<int:pk>/', PeopleDetailView.as_view(), name='people_detail')]

movies/models.py
from django.conf import settings
from django.db import models
from django.db.models import Count, Q
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from bloodeal.settings import CLOUDINARY_PREFIX_URL
from people.models import People


# Create your models here.
class Movie(models.Model):
    """
    A model that represents an actor or director.
    """
    title_vf = models.CharField(max_length=200,
                                blank=True,
                                null=True)
    title_vo = models.CharField(max_length=200,
                                blank=True,
                                null=True)
    slug = models.SlugField(max_length=200,
                            unique=False,
                            blank=True)
    release_year = models.IntegerField(blank=True,
                                       null=True)
    imdb_id = models.CharField(max_length=9,
                               blank=True,
                               null=True,
                               unique=True)
    movie_image = models.ImageField(null=True,
                                    blank=True,
                                    upload_to="movies/")
    requested_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                     on_delete=models.CASCADE,
                                     related_name='movie_requested_by',
                                     blank=True,
                                     null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:

        verbose_name = "Film"

    def __str__(self):

        return f"{self.title_vf}"

    def directors(self):

        directors = MovieDirector.objects.filter(movie=self)
        directors = [director.director for director in directors]

        return directors

    def actors(self):

        actors = MovieActor.objects.filter(movie=self)
        actors = [actor.actor for actor in actors]

        return actors

    def save(self, **kwargs):

        if not self.slug or self.slug == "none":
            self.slug = slugify(self.title_vf)

        return super(Movie, self).save(**kwargs)

    def image_tag(self):

        if self.movie_image != '':
            cloudinary_url = CLOUDINARY_PREFIX_URL + self.movie_image.name

            return mark_safe('<img src="%s" height="100px" />' % cloudinary_url)


class MovieDirector(models.Model):
    """
    A model that represents Director(s) of a movie
    """

    movie = models.ForeignKey(Movie, on_delete=models.CASCADE,
                              related_name='movie_director')
    director = models.ForeignKey(People, on_delete=models.CASCADE,
                                 related_name='director')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:

        verbose_name = "Réalisateur par film"
        verbose_name_plural = "Réalisateurs par film"
        unique_together = ("movie", "director")


class MovieActor(models.Model):
    """
    A model that represents Actor(s) of a movie
    """

    movie = models.ForeignKey(Movie, on_delete=models.CASCADE,
                              related_name='movie_actor')
    actor = models.ForeignKey(People, on_delete=models.CASCADE,
                              related_name='actor')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:

        verbose_name = "Acteur par film"
        verbose_name_plural = "Acteurs par film"
        unique_together = ("movie", "actor")


def get_movies(user=None):

    movies = Movie.objects.all()
    top_movies = movies.annotate(num_favorites=Count("favorite_movie")).order_by("-num_favorites")
    favorite_movies = movies.filter(favorite_movie__user=user)

    return {"movies": movies,
            "top_movies": top_movies,
            "favorite_movies": favorite_movies,
            "latest_movies": movies.exclude(movie_image="").order_by("-date_created")}


def get_movies_results(keyword):

    movies_results = Movie.objects.filter(Q(title_vf__icontains=keyword) | Q(title_vo__icontains=keyword))

    return {"movies_results": movies_results}


def get_user_requested_movies(user):

    movies = Movie.objects.filter(requested_by=user)

    return {"user_requested_movies": movies}

movies/views.py
from django.contrib import messages
from django.views.generic import ListView, DetailView

from profiles.models import get_user_all_favorites
from deals.models import Deal
from blurays.models import BluRay, get_blurays
from user_requests.forms import generate_initialized_request_forms
from user_requests.models import get_user_requests_total
from .models import Movie, get_movies


# Create your views here.
class MovieListView(ListView):
    model = Movie
    template_name = "movies/movies_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MovieListView, self).get_context_data(**kwargs)

        if not self.request.user.is_anonymous:
            context.update(get_movies(self.request.user))
            # Récupère les données pour le bloc central
            context.update(get_user_all_favorites(self.request.user))
            requests_forms = generate_initialized_request_forms(self.request.user)
            context.update(requests_forms)
            context.update(get_user_requests_total(self.request.user))

        else:
            context.update(get_movies())

        return context


class MovieDetailView(DetailView):
    model = Movie
    template_name = "movies/movies_detail.html"

    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}

        if self.object:
            context["object"] = self.object
            context_object_name = self.get_context_object_name(self.object)

            if context_object_name:
                context[context_object_name] = self.object

        movie_blurays = BluRay.objects.filter(movie=self.object)
        deals = Deal.objects.filter(bluray__in=movie_blurays)
        context.update({"movie_blurays": movie_blurays,
                        "deals": deals})
        context.update(get_movies())
        context.update(get_blurays())
        # Récupère un message à afficher dans la fenêtre modale le cas échéant
        storage = messages.get_messages(self.request)

        if storage:
            context.update({"modal": "modal.html",
                            "modal_content": storage})

        if not self.request.user.is_anonymous:
            # Récupère les données pour le bloc central
            context.update(get_user_all_favorites(self.request.user))
            context.update(get_user_requests_total(self.request.user))

        return super().get_context_data(**context)

movies/templates/movies/all-movies-snippet.html
{% load static %}

<div class="dashboard-block-element min-height-30vh">
    {% if movie_list %}
    <div class="dashboard-block-element-title">
        <h2>TOUS LES FILMS ({{ movie_list|length }})</h2>
    </div>
    <div class="dashboard-block-element-content flex-wrap">
    {% for movie in movie_list %}
    <div class="capsule capsule-all width-25 margin-bottom-1rem">
        {% if movie.movie_image %}
            <div class="capsule-image" style="background-image: url({{ movie.movie_image.url }});">
        {% else %}
            <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
        {% endif %}
        {% if user.is_authenticated %}
            <div class="favorite-wrapper">
                <div class="favorite" onclick="favorite('movie_{{ movie.pk }}',{{ movie.pk }}, 'movie')" id="movie_{{ movie.pk }}">
                    <svg class="favorite-svg-heart {% if movie in user_favorite_movies %}press{% endif %}" viewBox="0 0 24 24">
                      <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                    </svg>
                </div>
            </div>
        {% endif %}
        </div>
        <div class="capsule-text">
            <h2><a href="{% url 'movies:movies_detail' slug=movie.slug pk=movie.pk %}">{{ movie|truncatechars:30 }}</a></h2>
            {% if movie.release_year %}
            <p>{{ movie.release_year }}</p>
            {% endif %}
            {% if movie.directors %}
                <p>De
                {% for director in movie.directors %}<a href="{% url 'people:people_detail' slug=director.slug pk=director.pk %}">{{ director }}</a>
                {% endfor %}</p>
            {% endif %}
            {% if movie.actors %}
                <p>Avec
                    {% for actor in movie.actors %}<a href="{% url 'people:people_detail' slug=actor.slug pk=actor.pk %}">{{ actor }}</a>
                {% endfor %}</p>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    </div>
    {% if movie_list|length > 4 %}
        <p id="loadMore-container" class="loadMore-container"><a href="#" id="loadMore">Voir tout</a></p>
    {% endif %}
    {% else %}
      <div class="capsule justify-content-center margin-auto">
        <h2 class="margin-1rem width-100 text-align-center">Aucun film n'est enregistré dans notre base de données.</h2>
    </div>
    {% endif %}
</div>

movies/templates/movies/detail-main-block.html
{% load static %}

<section class="dashboard-block main-block-min-width">

    <div class="dashboard-block-element min-height-30vh">
        {% if deals %}
        <div class="dashboard-block-element-title">
            <h2>BONS PLANS SUR LE FILM {{ movie|upper }} ({{ deals|length }})</h2>
        </div>
        <div class="dashboard-block-element-content flex-wrap">
        {% for deal in deals %}
        <div class="capsule width-25 margin-bottom-1rem">
            {% if deal.bluray.bluray_image %}
                <div class="capsule-image" style="background-image: url({{ deal.bluray.bluray_image.url }});">
            {% else %}
                <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
            {% endif %}
            <a href="{{ deal.bluray.amazon_aff_link }}" target="_blank">
                <p class="deal-price {% if deal.status != '1' %}inactif{% endif %}">{{ deal.price }}€</p>
            </a>
            </div>
            <div class="capsule-text">
                <a href="{% url 'deals:deals_detail' pk=deal.pk %}">
                <h2>{{ deal.bluray.movie }}</h2>
                {% if deal.bluray.uhd %}
                    <p><img src="{% static 'img/logo-4k.png' %}" alt="Logo Blu-Ray 4K" width="100px"></p>
                {% endif %}
                <p>Posté le {{ deal.start_date|date:"d/m/Y"|title }}</p>
                </a>
            </div>
        </div>
        {% endfor %}
        </div>
        {% else %}
        <div class="capsule justify-content-center margin-auto">
            <h2>Aucun bon plan n'a été partagé pour ce film.</h2>
        </div>
        {% endif %}
    </div>

    <div class="dashboard-block-element min-height-30vh">
        {% if movie_blurays %}
        <div class="dashboard-block-element-title">
            <h2>BLU-RAYS DE {{ object|upper }} ({{ movie_blurays|length }})</h2>
        </div>
        <div class="dashboard-block-element-content flex-wrap">
        {% for bluray in movie_blurays %}
        <div class="capsule width-25 margin-bottom-1rem">
            {% if bluray.bluray_image %}
            <div class="capsule-image" style="background-image: url({{bluray.bluray_image.url }});">
            {% else %}
            <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
            {% endif %}
            {% if user.is_authenticated %}
                <div class="favorite-wrapper">
                    <div class="favorite" onclick="favorite('favorite_bluray_{{ bluray.pk }}',{{ bluray.pk }}, 'bluray')" id="favorite_bluray_{{ bluray.pk }}">
                        <svg class="favorite-svg-heart {% if bluray in user_favorite_blurays %}press{% endif %}" viewBox="0 0 24 24">
                          <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                        </svg>
                    </div>
                </div>
            {% endif %}
            </div>
            <div class="capsule-text">
                <a href="{% url 'blurays:blurays_detail' slug=bluray.slug pk=bluray.pk %}">
                    {% if bluray.title %}
                        <h2>{{ bluray.title }}</h2>
                    {% else %}
                        <h2>{{ bluray.movie }}</h2>
                    {% endif %}
                    {% if bluray.uhd %}
                        <p><img src="{% static 'img/logo-4k.png' %}" alt="Logo Blu-Ray 4K" width="100px"></p>
                    {% endif %}
                    <p>Sortie: {{ bluray.release_date|date:"d/m/Y" }}</p>
                </a>
            </div>
        </div>
        {% endfor %}
        </div>
        {% else %}
        <div class="capsule justify-content-center margin-auto">
            <h2>Aucun blu-ray n'est enregistré pour ce film.</h2>
        </div>
        {% endif %}
    </div>

</section>

movies/templates/movies/detail-right-block.html
{% load static %}

<section class="dashboard-block side-block-min-width mobile-display-none">
    {% include 'movies/top-five-snippet.html' %}
</section>

movies/templates/movies/favorite-movies-snippet.html
{% load static %}

<div class="dashboard-block-element min-height-30vh">
    {% if user_favorite_movies %}
    <div class="dashboard-block-element-title">
        <h2 class="padding-1rem">VOS FILMS PREFERES ({{ user_favorite_movies|length }})</h2>
    </div>
    <div class="dashboard-block-element-content flex-wrap">
    {% for user_favorite_movie in user_favorite_movies %}
    <div class="capsule width-25 margin-bottom-1rem">
            {% if user_favorite_movie.movie_image %}
                <div class="capsule-image" style="background-image: url({{ user_favorite_movie.movie_image.url }});">
                {% else %}
                <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
            {% endif %}
            {% if user.is_authenticated %}
                <div class="favorite-wrapper">
                    <div class="favorite" onclick="favorite('user_favorite_movie_{{ user_favorite_movie.pk }}',{{ user_favorite_movie.pk }}, 'movie')" id="user_favorite_movie_{{ user_favorite_movie.pk }}">
                        <svg class="favorite-svg-heart {% if user_favorite_movie in user_favorite_movies %}press{% endif %}" viewBox="0 0 24 24">
                          <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                        </svg>
                    </div>
                </div>
            {% endif %}
            </div>
            <div class="capsule-text">
                <a href="{% url 'movies:movies_detail' slug=user_favorite_movie.slug pk=user_favorite_movie.pk %}">
                <h2>{{ user_favorite_movie|truncatechars:30 }}</h2>
                </a>
                {% if user_favorite_movie.release_year %}
                <p>Sorti en {{ user_favorite_movie.release_year }}</p>
                {% endif %}
            </div>
    </div>
    {% endfor %}
    </div>
    {% else %}
    <div class="capsule justify-content-center margin-auto">
        {% if user.is_authenticated %}
            <h2 class="margin-1rem text-align-center">Vous n'avez aucun film dans vos favoris.</h2>
        {% else %}
            <h2 class="margin-1rem text-align-center">Connectez-vous pour marquer des films comme favoris.</h2>
        {% endif %}
    </div>
    {% endif %}
</div>

movies/templates/movies/latest-movie-snippet.html
{% load static %}

<div class="dashboard-block-element min-height-20vh padding-1rem text-align-center justify-content-center">
    {% if latest_movies %}
    <h2>Gros plan sur ...</h2>
    {% with latest_movies|first as latest_movie %}
    <div class="capsule align-items-center flex-wrap flex-column">
                {% if latest_movie.movie_image %}
                <div class="capsule-image margin-auto" style="background-image: url({{ latest_movie.movie_image.url }});">
                {% else %}
                <div class="capsule-image margin-auto" style="background-image: url({% static 'img/nopic.jpg' %});">
                {% endif %}
                    {% if user.is_authenticated %}
                    <div class="favorite-wrapper">
                        <div class="favorite" onclick="favorite('latest_movie_{{ latest_movie.pk }}',{{ latest_movie.pk }}, 'movie')" id="latest_movie_{{ latest_movie.pk }}">
                            <svg class="favorite-svg-heart {% if latest_movie in favorite_movies %}press{% endif %}" viewBox="0 0 24 24">
                              <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                            </svg>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <div class="capsule-text margin-auto text-align-center width-100">
                    <p>
                        {% if latest_movie.slug %}
                        <a href="{% url 'movies:movies_detail' slug=latest_movie.slug pk=latest_movie.pk %}">
                            <h2 class="justify-content-center">{{ latest_movie|truncatechars:40 }}</h2>
                        </a>
                        {% else %}
                            <h2 class="justify-content-center">{{ latest_movie|truncatechars:40 }}</h2>
                        {% endif %}
                    </p>
                    {% if latest_movie.directors %}
                    <p>Un film de {% for director in latest_movie.directors %}
                        {% if director.slug %}
                        <a href="{% url 'people:people_detail' slug=director.slug pk=director.pk %}">
                            {{ director }}
                        </a>
                        {% else %}
                            {{ director }}
                        {% endif %}
                        {% endfor %}
                    </p>
                    {% endif %}
                    {% if latest_movie.actors %}
                    <p>Avec {% for actor in latest_movie.actors %}
                        {% if actor.slug %}
                        <a href="{% url 'people:people_detail' slug=actor.slug pk=actor.pk %}">
                            {{ actor }}
                        </a>
                        {% else %}
                            {{ actor }}
                        {% endif %}
                        {% endfor %}
                    </p>
                    {% endif %}
                </div>{% endwith %}
            </div>
    {% else %}
        <p>Il n'y a actuellement aucun film dans notre base de données.</p>
    {% endif %}
</div>

movies/templates/movies/movie-counter.html
{% load static %}

{% if movie_list %}
<div class="dashboard-block-element justify-content-center padding-1rem">
    <div class="dashboard-block-element-content justify-content-center flex-wrap">
        <div class="capsule-text text-align-center width-100">
            <p class="counter" total="{{ movie_list|length }}">0</p>
            <br>films disponibles sur Bloodeal.
        </div>
    </div>
</div>
{% else %}
{% endif %}

movies/templates/movies/movie-snippet.html
{% load static %}

{% if movie %}
<div class="dashboard-block-element min-height-20vh padding-1rem">
    <div class="dashboard-block-element-content flex-wrap">
        <div class="capsule-text">
            <p>
                <a style="padding: 0;" href="{% url 'movies:movies_detail' slug=movie.slug pk=movie.pk %}">
                    <h2>{{ movie }}</h2>
                </a>
            {% if movie.movie_image %}
            <img src="{{ movie.movie_image.url }}" alt="{{ movie }}" width="75px">
            {% endif %}
            </p>

            {% if movie.imdb_id %}
                <span class="imdbRatingPlugin" data-user="ur113694504" data-title="{{ movie.imdb_id }}" data-style="p4">
                    <a href="https://www.imdb.com/title/{{ movie.imdb_id }}/?ref_=plg_rt_1">
                        <img src="https://ia.media-imdb.com/images/G/01/imdb/plugins/rating/images/imdb_37x18.png" alt="{{ movie }}" />
                    </a>
                </span>
            <script id="imdb"></script>
            {% endif %}
            {% if movie.release_year %}
            <p>{{ movie.release_year }}</p>
            {% endif %}
            {% if movie.directors %}
            <p>Un film de {% for director in movie.directors %}
                <a href="{% url 'people:people_detail' slug=director.slug pk=director.pk %}">{{ director }}</a> {% endfor %}</p>
            {% endif %}
            {% if movie.actors %}
            <p>Avec {% for actor in movie.actors %}
                <a href="{% url 'people:people_detail' slug=actor.slug pk=actor.pk %}">{{ actor }}</a> {% endfor %}</p>
            {% endif %}
        </div>
    </div>
</div>
{% endif %}

movies/templates/movies/recommended-movies-snippet.html
{% load static %}

<div class="dashboard-block-element min-height-30vh">
    {% if user_recommended_movies %}
    <div class="dashboard-block-element-title">
        <h2 class="padding-1rem">NOS RECOMMANDATIONS DE FILMS ({{ user_recommended_movies|length }})</h2>
    </div>
    <div class="dashboard-block-element-content flex-wrap">
    {% for user_recommended_movie in user_recommended_movies %}
    <div class="capsule width-25 margin-bottom-1rem">
            {% if user_recommended_movie.movie_image %}
                <div class="capsule-image" style="background-image: url({{ user_recommended_movie.movie_image.url }});">
                {% else %}
                <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
            {% endif %}
            {% if user.is_authenticated %}
                <div class="favorite-wrapper">
                    <div class="favorite" onclick="favorite('user_recommended_movie_{{ user_recommended_movie.pk }}',{{ user_recommended_movie.pk }}, 'movie')" id="user_recommended_movie_{{ user_recommended_movie.pk }}">
                        <svg class="favorite-svg-heart {% if user_recommended_movie in user_favorite_movies %}press{% endif %}" viewBox="0 0 24 24">
                          <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                        </svg>
                    </div>
                </div>
            {% endif %}
            </div>
            <div class="capsule-text">
                <a href="{% url 'movies:movies_detail' slug=user_recommended_movie.slug pk=user_recommended_movie.pk %}">
                <h2>{{ user_recommended_movie|truncatechars:30 }}</h2>
                </a>
                <p>Sorti en {{ user_recommended_movie.release_year }}</p>
            </div>
    </div>
    {% endfor %}
    </div>
    {% else %}
    <div class="capsule justify-content-center margin-auto flex-wrap">
        {% if user.is_authenticated %}
            <h2 class="margin-1rem text-align-center width-100">Nous n'avons aucune recommandation de films pour vous. </h2>
            <br>
            <h2 class="margin-1rem text-align-center width-100">Pensez à ajouter des personnalités à vos favoris.</h2>
        {% else %}
            <h2 class="margin-1rem text-align-center">Connectez-vous pour bénéficier de recommandations de films.</h2>
        {% endif %}
    </div>
    {% endif %}
</div>

movies/templates/movies/top-five-snippet.html
{% load static %}

{% if top_movies %}
<div class="dashboard-block-element min-height-20vh justify-content-center">
    <div class="dashboard-block-element-title">
        <h2>TOP 5</h2>
    </div>
    <div class="dashboard-block-element-content flex-column">
    {% for movie in top_movies|slice:":5" %}
    <div class="capsule align-items-center flex-column width-100">
        {% if movie.movie_image %}
        <div class="capsule-image" style="background-image: url({{ movie.movie_image.url }});">
        {% else %}
        <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
        {% endif %}
        {% if user.is_authenticated %}
            <div class="favorite-wrapper">
                <div class="favorite" onclick="favorite('top_movie_{{ movie.pk }}',{{ movie.pk }}, 'movie')" id="top_movie_{{ movie.pk }}">
                    <svg class="favorite-svg-heart {% if movie in user_favorite_movies %}press{% endif %}" viewBox="0 0 24 24">
                      <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                    </svg>
                </div>
            </div>
        {% endif %}
        </div>
        <div class="capsule-text text-align-center">
            <h2 class="justify-content-center"><a href="{% url 'movies:movies_detail' slug=movie.slug pk=movie.pk %}">{{ movie|truncatechars:90 }}</a></h2>
            {% with total=movie.num_favorites %}
                ♥ par {{ total }} membre{{total|pluralize}}
            {% endwith %}
        </div>
    </div>
    {% endfor %}
    </div>
</div>
{% else %}
{% endif %}