accounts/urls.py
from django.urls import path

from deals.views import DealListView
from .views import (
    index_view,
    SignupView,
    account_created_view,
    authenticate_view,
    login_view,
    logout_view,
    dashboard_view,
    SearchResultsView,
    help_view,
    contact_view,
    send_message_view,
    DeleteAccountView)

# Création d'un espace de noms
app_name = 'accounts'

urlpatterns = [
    path('', index_view, name="index"),
    path('authenticate', authenticate_view, name="authenticate"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('account-created/', account_created_view, name="account_created"),
    path('delete-account/<int:pk>/', DeleteAccountView.as_view(), name="delete_account"),
    path('login/', login_view, name="login"),
    path('dashboard/', dashboard_view, name="dashboard"),
    path('logout/', logout_view, name="logout"),
    path('search/', SearchResultsView.as_view(), name="search_results"),
    path('help/', help_view, name="help"),
    path('contact/', contact_view, name="contact"),
    path('send-message/', send_message_view, name="send_message")]

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView)

from .views import (
    CustomUserViewSet,
    BluRayViewSet,
    MovieViewSet,
    MovieDirectorViewSet,
    MovieActorViewSet,
    PeopleViewSet,
    DealViewSet,
    FavoriteBluRayViewSet,
    FavoriteMovieViewSet,
    FavoritePeopleViewSet,
    BluRayRequestViewSet,
    MovieRequestViewSet,
    PeopleRequestViewSet,
    DealRequestViewSet)

app_name = "api"

router = DefaultRouter()
router.APIRootView.__name__ = "Bloodeal"
router.APIRootView.__doc__ = "API de l'application Bloodeal"
router.register(r'users', CustomUserViewSet)
router.register(r'blurays', BluRayViewSet)
router.register(r'movies', MovieViewSet, basename="movies")
router.register(r'movies_directors', MovieDirectorViewSet)
router.register(r'movies_actors', MovieActorViewSet)
router.register(r'people', PeopleViewSet)
router.register(r'deals', DealViewSet)
router.register(r'favorite_blurays', FavoriteBluRayViewSet)
router.register(r'favorite_movies', FavoriteMovieViewSet)
router.register(r'favorite_people', FavoritePeopleViewSet)
router.register(r'bluray_requests', BluRayRequestViewSet)
router.register(r'movie_requests', MovieRequestViewSet)
router.register(r'people_requests', PeopleRequestViewSet)
router.register(r'deal_requests', DealRequestViewSet)

urlpatterns = [
    path('login/', TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path('login/refresh/', TokenRefreshView.as_view(), name="token_refresh"),
    path('v1/', include(router.urls)),
    path('v1/', router.APIRootView.as_view(), name="v1"),
]

bloodeal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from accounts.views import sentry_error, generate_pdf

favicon_view = RedirectView.as_view(url='/static/img/favicon.png',
                                    permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('', include("accounts.urls"), name="accounts"),
    path('profiles/', include("profiles.urls"), name="profiles"),
    path('blurays/', include("blurays.urls"), name="blurays"),
    path('deals/', include("deals.urls"), name="deals"),
    path('movies/', include("movies.urls"), name="movies"),
    path('people/', include("people.urls"), name="people"),
    path('requests/', include("user_requests.urls"), name="user_requests"),
    path('api/', include("api.urls"), name="api"),
    path('site-admin/', admin.site.urls),
    path('sentry-debug/', sentry_error, name="sentry"),
    path('pdf/', generate_pdf, name="pdf"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blurays/urls.py
from django.urls import path

from blurays.views import BluRayListView, BluRayDetailView

# Création d'un espace de noms
app_name = 'blurays'

urlpatterns = [path('list/', BluRayListView.as_view(), name="blurays_list"),
               path('<str:slug>/<int:pk>/', BluRayDetailView.as_view(), name="blurays_detail")]

movies/urls.py
from django.urls import path

from movies.views import MovieListView, MovieDetailView


# Création d'un espace de noms
app_name = 'movies'

urlpatterns = [path("list/", MovieListView.as_view(), name="movies_list"),
               path("<str:slug>/<int:pk>/", MovieDetailView.as_view(), name="movies_detail")]

people/urls.py
from django.urls import path

from .views import PeopleListView, PeopleDetailView


# Création d'un espace de noms
app_name = 'people'

urlpatterns = [path('list/', PeopleListView.as_view(), name='people_list'),
               path('<str:slug>/<int:pk>/', PeopleDetailView.as_view(), name='people_detail')]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


# Create your models here.
class CustomUserManager(BaseUserManager):
    """
    Define a model manager for CustomUser model with no username field.
    """

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a CustomUser with the given email and password."""

        if not email:
            raise ValueError('Vous devez saisir une adresse email valide.')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password=None, **extra_fields):
        """
        Create and save a regular CustomUser with the given email and
        password.
        """

        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    """
    A model that represents a user
    """

    username = None
    first_name = models.CharField(max_length=200,
                                  blank=True,
                                  null=True)
    last_name = models.CharField(max_length=200,
                                 blank=True,
                                 null=True)
    email = models.EmailField(unique=True)
    pseudo = models.CharField(max_length=24,
                              blank=True,
                              null=True,
                              unique=True,
                              error_messages={'unique': 'Ce pseudo est déjà pris.'})

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:

        verbose_name = "Utilisateur"

    def __str__(self):

        name = self.pseudo if self.pseudo else self.email

        return f"{name}"

    def join_date(self):
        return self.date_joined.strftime("%d/%m/%Y")

accounts/views.py
import smtplib
import io

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect, FileResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView
from reportlab.pdfbase.pdfmetrics import stringWidth, getRegisteredFontNames
from reportlab.pdfgen import canvas
from reportlab.rl_settings import defaultPageSize

from accounts.models import CustomUser
from bloodeal.settings import EMAIL_HOST_USER
from accounts.forms import LoginForm, SignupForm
from deals.models import get_deals, get_user_favorites_deals
from movies.models import get_movies, get_movies_results
from blurays.models import get_blurays, BluRay, get_blurays_results
from people.models import get_people_results
from profiles.models import get_user_all_favorites, get_user_suggested_blurays
from user_requests.forms import generate_initialized_request_forms
from user_requests.models import get_user_requests_total, get_user_requests


# Create your views here.
def index_view(request):
    """
    A function-based view that redirects to two different views:
    -> login_view if user is not authenticated
    -> dashboard_view if user is authenticated

    Template:
        None
    """
    if request.user.is_authenticated:

        return redirect("accounts:dashboard")

    else:

        return redirect("deals:deals_list")


def authenticate_view(request):
    next_url = request.GET.get("next", "accounts:dashboard")

    if request.user.is_authenticated:

        return redirect("accounts:dashboard")

    elif request.method == "POST" and request.POST["button"] == "Je me connecte":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)

            return redirect(next_url)

        else:
            login_form = LoginForm(auto_id="login_%s")
            signup_form = SignupForm(auto_id="signup_%s")
            login_message = "Adresse email et/ou mot de passe non  valide."
            context = {"login_form": login_form,
                       "signup_form": signup_form,
                       "login_message": login_message,
                       "next": next_url}

            return render(request, "accounts/index.html", context)

    elif request.method == "POST" and request.POST["button"] == "Je m'inscris":
        signup_form = SignupForm(request.POST)

        if signup_form.is_valid():
            signup_form.save()
            username = request.POST["email"]
            password = request.POST["password1"]
            user = authenticate(request, username=username, password=password)
            login(request, user)
            message = "Merci de votre inscription !"
            storage = [message]
            context = {"modal": "modal.html",
                       "modal_content": storage}
            # Récupère les données pour le bloc de droite
            context.update(get_movies(request.user))
            context.update(get_blurays(request.user))
            # Récupère les données pour le bloc de gauche
            requests_forms = generate_initialized_request_forms(request.user)
            context.update(requests_forms)
            # Récupère les données pour le bloc central
            context.update(get_user_all_favorites(request.user))
            # Récupère le nombre de demandes de l'utilisateur
            context.update(get_user_requests_total(request.user))

            return render(request, "accounts/dashboard.html", context)

    else:
        login_form = LoginForm(auto_id="login_%s")
        signup_form = SignupForm(auto_id="signup_%s")
        context = {"login_form": login_form,
                   "signup_form": signup_form}
        storage = messages.get_messages(request)

        if storage:
            context.update({"modal": "modal.html",
                            "modal_content": storage})

        return render(request, "accounts/index.html", context)


def login_view(request):
    """
    A function-based view for user to login.

    Context:
        next: next url to redirect user once logged in
        form:  :form:"accounts.LoginForm"
        message: A string displayed to ask user to login

    Template:
        :template:"accounts/login.html"
    """
    next_url = request.GET.get("next", "accounts:dashboard")
    context = {"next": next_url}

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)

            return redirect(next_url)

        else:
            form = LoginForm
            context["form"] = form
            context["message"] = "Adresse email ou mot de passe non valide."

            return render(request, "accounts/login.html", context)

    else:
        form = LoginForm()
        context["form"] = form

        return render(request, "accounts/login.html", context)


class SignupView(CreateView):
    """
    A class-based view for a visitor to signup.

    Context:
        form:  :form:"accounts.SignupForm"

    Template:
        :template:"accounts/signup.html"
    """
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = "../account-created/"

    def form_valid(self, form):
        # Override form_valid function from parent class to add automatic login
        # after signup
        form.save()
        username = self.request.POST["email"]
        password = self.request.POST["password1"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        message = "Merci de votre inscription !"
        storage = [message]
        context = {"modal": "modal.html",
                   "modal_content": storage}
        # Récupère le nombre de demandes de l'utilisateur
        context.update(get_user_requests_total(self.request.user))

        return render(self.request, "accounts/dashboard.html", context)


@login_required
def account_created_view(request):
    """
    A function-based view to display a confirmation message once user account
    has been created.

    Context:
        None

    Template:
        :template:"accounts/account-created.html"
    """
    context = {}

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)

    return render(request, "accounts/account-created.html", context)


class DeleteAccountView(DeleteView):
    """
    A class-based view for a user to delete his/her account.

    Context:
        form:  :form:"accounts.SignupForm"

    Template:
        :template:"accounts/delete-account.html"
    """
    model = CustomUser
    # form_class = DeleteAccountForm
    template_name = "accounts/delete-account.html"
    success_url = reverse_lazy("accounts:index")

    def post(self, request, *args, **kwargs):

        # Override form_valid function from parent class to add automatic login
        # after signup
        if self.kwargs.get("pk") == self.request.user.pk:
            message = "Votre compte a bien été supprimé ! A bientôt !"
            messages.add_message(self.request,
                                 level=messages.INFO,
                                 message=message)
            user = CustomUser.objects.filter(pk=self.request.user.pk)
            user.delete()

            return HttpResponseRedirect(reverse_lazy("accounts:index"))

        else:
            message = "Vous ne pouvez pas supprimé le compte d'un autre."
            messages.add_message(self.request,
                                 level=messages.INFO,
                                 message=message)

            return HttpResponseRedirect(reverse_lazy("accounts:index"))


def logout_view(request):
    """
    A function-based view to logout user.

    Context:
        None

    Template:
        None
    """
    logout(request)

    return redirect("accounts:index")


@login_required
def dashboard_view(request):
    # Récupère les données pour le bloc de droite
    context = get_deals()
    context.update(get_movies(request.user))
    context.update(get_blurays(request.user))
    # Récupère les données pour le bloc de gauche
    requests_forms = generate_initialized_request_forms(request.user)
    context.update(requests_forms)
    # Récupère les blu-rays recommandés selon les favoris de l'utilisateur
    context.update(get_user_all_favorites(request.user))
    # Récupère les bons plans recommandés selon les favoris de l'utilisateur
    context.update(get_user_favorites_deals(request.user))
    # # Récupère les suggestions de blurays pour l'utilisateur
    context.update(get_user_suggested_blurays(request.user))
    # Récupère les messages le cas échéant et les envoie à la fenêtre modale
    storage = messages.get_messages(request)

    if storage:
        context.update({"modal": "modal.html",
                        "modal_content": storage})

    # Récupère le nombre de demandes de l'utilisateur
    context.update(get_user_requests(request.user))
    # Récupère le nombre de demandes de l'utilisateur pour la navbar
    context.update(get_user_requests_total(request.user))

    return render(request, "accounts/dashboard.html", context)


class SearchResultsView(ListView):
    template_name = "accounts/search_results.html"
    queryset = BluRay.objects.none()

    def get_keyword(self):

        return self.request.GET.get("Q", "")

accounts/templates/accounts/account-created.html
{% extends "base.html" %}
{% load static %}

{% block left-block %}
{% endblock %}

{% block content %}
{% if modal %}
    {% include modal %}
{% endif %}
<section class="dashboard-block main-block-min-width">
    <div class="dashboard-block-element min-height-30vh justify-content-center">
        <div class="dashboard-block-element-title">
            <p class="signup-confirmation"><h2>Merci de vous êtes inscrit sur Bloodeal !</h2></p>
        </div>
        <div class="dashboard-block-element-content flex-wrap justify-content-center">
            <a href="{% url 'accounts:dashboard' %}">
                <button class="btn btn-submit ">Revenir à l'accueil</button>
            </a>
        </div>
    </div>
</section>
{% endblock %}

{% block right-block %}
{% endblock %}

accounts/templates/accounts/contact.html
{% extends "base.html" %}
{% load static %}

    {% block left-block %}
        {% include "profiles/left-block.html" %}
    {% endblock %}

    {% block content %}
    {% if modal %}
        {% include modal %}
    {% endif %}
    <section class="dashboard-block main-block-min-width">

        <div class="dashboard-block-element min-height-30vh">
            <div class="dashboard-block-element-title">
                <h2>CONTACT</h2>
            </div>
            <div class="dashboard-block-element-content flex-wrap width-25">
                <form method="post" action="{% url 'accounts:send_message' %}">
                    {% csrf_token %}
                    <label for="formulaire_nom">Prénom + Nom</label>
                    <input id="formulaire_nom" type="text" name="formulaire_nom" placeholder="Entrez votre nom complet" />
                    <br>
                    <label for="formulaire_email">Adresse email</label>
                    <input id="formulaire_email" type="email" name="formulaire_email" placeholder="Entrez votre adresse email" />
                    <br>
                    <label for="formulaire_message">Message</label>
                    <textarea id="formulaire_message" name="formulaire_message" cols="30" rows="10" placeholder="Entrez votre message ici"></textarea>
                    <br>
                    <label id="formulaire_label" for="formulaire_bloodeal">Prouvez que vous n'êtes pas un 🤖:
                    <input id="formulaire_bloodeal" type="text" name="formulaire_bloodeal" placeholder="Ecrivez BLOODEAL dans ce champ" required /></label>
                    <br>
                    <button class="padding-1rem margin-1rem" type="submit" name="formulaire_envoyer">📪 Envoyer</button>
                </form>
            </div>
        </div>

    </section>
    {% endblock %}

    {% block right-block %}
        {% include "profiles/right-block.html" %}
    {% endblock %}

accounts/templates/accounts/dashboard.html
{% extends "base.html" %}
{% load static %}
{% load profiles_tags %}

    {% block left-block %}
        {% include "profiles/left-block.html" %}
    {% endblock %}

    {% block content %}
    {% if modal %}
        {% include modal %}
    {% endif %}

    <section class="dashboard-block main-block-min-width">
        {% include 'deals/recommended-deals-snippet.html' %}
        {% include 'blurays/recommended-blurays-snippet.html' %}
        {% include 'blurays/favorite-blurays-snippet.html' %}
    </section>
    {% endblock %}

    {% block right-block %}
        {% include "profiles/right-block.html" %}
    {% endblock %}

accounts/templates/accounts/delete-account.html
{% extends "base.html" %}
{% load static %}

{% block left-block %}
{% endblock %}

{% block content %}
{% if modal %}
    {% include modal %}
{% endif %}
<div class="flex-column height-fit-content">
    <section class="dashboard-block main-block-min-width">

        <div class="dashboard-block-element margin-1rem">
            <div class="dashboard-block-element-title">
                <h2>CONFIRMEZ LA SUPPRESSION DE VOTRE COMPTE</h2>
            </div>
            <div class="dashboard-block-element-content flex-wrap padding-1rem text-align-center">
                <form method="POST">
                    {% csrf_token %}
                        <p>
                            <input class="btn btn-delete" name="button" type="submit" value="JE ME DESINSCRIS">
                        </p>
                </form>
            </div>
        </div>

    </section>
</div>
{% endblock %}

{% block right-block %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

    {% if user.is_authenticated %}

        <section class="dashboard-block-element min-height-20vh width-25 justify-content-center margin-auto">
            <div class="dashboard-block-element-title">
                <h2>Vous êtes déjà inscrit sur notre site.</h2>
            </div>
            <div class="dashboard-block-element-content justify-content-center">
                <p>
                    <a href="{% url 'accounts:dashboard' %}"><buttom class="btn btn-submit">Revenir à l'accueil</buttom></a>
                </p>
            </div>
        </section>

    {% else %}

{% block header %}
{% endblock %}


{% block left-block %}
{% endblock %}

{% block content %}
{% if modal %}
    {% include modal %}
{% endif %}
<div class="flex-column height-fit-content">
    <h1 class="text-align-center">BL💿💿DEAL</h1>
    <section class="dashboard-block side-block-min-width index-page">

        <div class="dashboard-block-element margin-1rem height-fit-content">
            <div class="dashboard-block-element-title">
                <h2>CONNEXION</h2>
            </div>
            <div class="dashboard-block-element-content flex-wrap padding-1rem">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                            <p>{{ field.label_tag }}</p>
                            <p class="display-flex">{{ field }}
                                {% if forloop.counter == 2 %}
                                    <span class="show-password" onclick="showPassword('{{ field.auto_id }}')">👁</span>
                                {% endif %}
                            </p>
                            <br>
                    {% endfor %}
                        {% if login_message %}
                            <p class="errorlist">{{ login_message }}</p>
                            <br>
                        {% endif %}
                    <p class="btn"><input name="button" type="submit" value="Je me connecte" class="btn-submit"></p>
                </form>
            </div>
        </div>

    </section>
</div>
{% endblock %}

{% block right-block %}
{% endblock %}

{% endif %}

accounts/templates/accounts/search_results.html
{% extends "base.html" %}
{% load static %}
{% load profiles_tags %}

    {% block left-block %}
        {% include "profiles/left-block.html" %}
    {% endblock %}

    {% block content %}
    {% if modal %}
        {% include modal %}
    {% endif %}
    <section class="dashboard-block main-block-min-width">

        <div class="dashboard-block-element min-height-30vh">
            {% if blurays_results %}
            <div class="dashboard-block-element-title">
                <h2 class="padding-1rem">RESULTATS DE VOTRE RECHERCHE DANS LES BLU-RAYS ({{ blurays_results|length }})</h2>
            </div>
            <div class="dashboard-block-element-content flex-wrap">
            {% for blurays_result in blurays_results %}
        <div class="capsule width-25 margin-bottom-1rem">
                {% if blurays_result.bluray_image %}
                    <div class="capsule-image" style="background-image: url({{ blurays_result.bluray_image.url }});">
                    {% else %}
                    <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
                {% endif %}
                {% if user.is_authenticated %}
                    <div class="favorite-wrapper">
                        <div class="favorite" onclick="favorite('blurays_result_{{ blurays_result.pk }}',{{ blurays_result.pk }}, 'bluray')" id="blurays_result_{{ blurays_result.pk }}">
                            <svg class="favorite-svg-heart {% if blurays_result in user_favorite_blurays %}press{% endif %}" viewBox="0 0 24 24">
                              <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                            </svg>
                        </div>
                    </div>
                {% endif %}
                </div>
                <div class="capsule-text">
                    <a href="{% url 'blurays:blurays_detail' slug=blurays_result.slug pk=blurays_result.pk %}">
                    {% if blurays_result.title %}
                        <h2>{{ blurays_result.title }}</h2>
                    {% else %}
                        <h2>{{ blurays_result.movie }}</h2>
                    {% endif %}
                    </a>
                    {% if blurays_result.release_date %}
                    <p>Sortie: {{ blurays_result.release_date|date:"d/m/Y" }}</p>
                    {% endif %}
                    <p><a href="{{ blurays_result.amazon_aff_link }}" target=_blank">Acheter sur Amazon</a></p>
                </div>
        </div>
            {% endfor %}
            </div>
            {% else %}
            <div class="capsule justify-content-center text-align-center margin-auto padding-1rem">
                <h2>Nous n'avons trouvé aucun résultat dans les blu-rays pour le mot clé "{{ keyword }}".</h2>
            </div>
            {% endif %}
        </div>

        <div class="dashboard-block-element min-height-30vh">
            {% if movies_results %}
            <div class="dashboard-block-element-title">
                <h2 class="padding-1rem">RESULTATS DE VOTRE RECHERCHE DANS LES FILMS ({{ movies_results|length }})</h2>
            </div>
            <div class="dashboard-block-element-content flex-wrap">
            {% for movies_result in movies_results %}
        <div class="capsule width-25 margin-bottom-1rem">
                {% if movies_result.movie_image %}
                    <div class="capsule-image" style="background-image: url({{ movies_result.movie_image.url }});">
                    {% else %}
                    <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
                {% endif %}
                {% if user.is_authenticated %}
                    <div class="favorite-wrapper">
                        <div class="favorite" onclick="favorite('movies_result_{{ movies_result.pk }}',{{ movies_result.pk }}, 'movie')" id="movies_result_{{ movies_result.pk }}">
                            <svg class="favorite-svg-heart {% if movies_result in user_favorite_movies %}press{% endif %}" viewBox="0 0 24 24">
                              <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                            </svg>
                        </div>
                    </div>
                {% endif %}
                </div>
                <div class="capsule-text">
                    <a href="{% url 'movies:movies_detail' slug=movies_result.slug pk=movies_result.pk %}">
                    <h2>{{ movies_result }}</h2>
                    </a>
                    {% if movies_result.release_year %}
                    <p>Sorti en {{ movies_result.release_year }}</p>
                    {% endif %}
                </div>
        </div>
            {% endfor %}
            </div>
            {% else %}
            <div class="capsule justify-content-center text-align-center margin-auto padding-1rem">
                <h2>Nous n'avons trouvé aucun résultat dans les films pour le mot clé "{{ keyword }}".</h2>
            </div>
            {% endif %}
        </div>

        <div class="dashboard-block-element min-height-30vh">
            {% if people_results %}
            <div class="dashboard-block-element-title">
                <h2 class="padding-1rem">RESULTATS DE VOTRE RECHERCHE DANS LES PERSONNALITES ({{ people_results|length }})</h2>
            </div>
            <div class="dashboard-block-element-content flex-wrap">
            {% for people_result in people_results %}
        <div class="capsule width-25 margin-bottom-1rem">
            {% if people_result.people_image %}
            <div class="capsule-image" style="background-image: url({{ people_result.people_image.url }});">
            {% else %}
            <div class="capsule-image" style="background-image: url({% static 'img/nopic.jpg' %});">
            {% endif %}
            {% if user.is_authenticated %}
                <div class="favorite-wrapper">
                    <div class="favorite" onclick="favorite('people_result_{{ people_result.pk }}',{{ people_result.pk }}, 'people')" id="people_result_{{ people_result.pk }}">
                        <svg class="favorite-svg-heart {% if people_result in user_favorite_people %}press{% endif %}" viewBox="0 0 24 24">
                          <path id="heart" d="M12 4.435c-1.989-5.399-12-4.597-12 3.568 0 4.068 3.06 9.481 12 14.997 8.94-5.516 12-10.929 12-14.997 0-8.118-10-8.999-12-3.568z" />
                        </svg>
                    </div>
                </div>
            {% endif %}
            </div>
            <div class="capsule-text">
                <a href="{% url 'people:people_detail' slug=people_result.slug pk=people_result.pk %}">
                    <h2>{{ people_result }}</h2>
                </a>
            </div>
        </div>
            {% endfor %}
            </div>
            {% else %}
            <div class="capsule justify-content-center text-align-center margin-auto padding-1rem">
                <h2>Nous n'avons trouvé aucun résultat dans les personnalités pour le mot clé "{{ keyword }}".</h2>
            </div>
            {% endif %}
        </div>

    </section>
    {% endblock %}

    {% block right-block %}
        {% include "profiles/right-block.html" %}
    {% endblock %}