accounts/urls.py
from django.urls import path

from deals.views import DealListView
from .views import (
    index_view,
    SignupView,
    account_created_view,
    authenticate_view,
    login_view,
    logout_view,
    dashboard_view,
    SearchResultsView,
    help_view,
    contact_view,
    send_message_view,
    DeleteAccountView)

# Création d'un espace de noms
app_name = 'accounts'

urlpatterns = [
    path('', index_view, name="index"),
    path('authenticate', authenticate_view, name="authenticate"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('account-created/', account_created_view, name="account_created"),
    path('delete-account/<int:pk>/', DeleteAccountView.as_view(), name="delete_account"),
    path('login/', login_view, name="login"),
    path('dashboard/', dashboard_view, name="dashboard"),
    path('logout/', logout_view, name="logout"),
    path('search/', SearchResultsView.as_view(), name="search_results"),
    path('help/', help_view, name="help"),
    path('contact/', contact_view, name="contact"),
    path('send-message/', send_message_view, name="send_message")]

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView)

from .views import (
    CustomUserViewSet,
    BluRayViewSet,
    MovieViewSet,
    MovieDirectorViewSet,
    MovieActorViewSet,
    PeopleViewSet,
    DealViewSet,
    FavoriteBluRayViewSet,
    FavoriteMovieViewSet,
    FavoritePeopleViewSet,
    BluRayRequestViewSet,
    MovieRequestViewSet,
    PeopleRequestViewSet,
    DealRequestViewSet)

app_name = "api"

router = DefaultRouter()
router.APIRootView.__name__ = "Bloodeal"
router.APIRootView.__doc__ = "API de l'application Bloodeal"
router.register(r'users', CustomUserViewSet)
router.register(r'blurays', BluRayViewSet)
router.register(r'movies', MovieViewSet, basename="movies")
router.register(r'movies_directors', MovieDirectorViewSet)
router.register(r'movies_actors', MovieActorViewSet)
router.register(r'people', PeopleViewSet)
router.register(r'deals', DealViewSet)
router.register(r'favorite_blurays', FavoriteBluRayViewSet)
router.register(r'favorite_movies', FavoriteMovieViewSet)
router.register(r'favorite_people', FavoritePeopleViewSet)
router.register(r'bluray_requests', BluRayRequestViewSet)
router.register(r'movie_requests', MovieRequestViewSet)
router.register(r'people_requests', PeopleRequestViewSet)
router.register(r'deal_requests', DealRequestViewSet)

urlpatterns = [
    path('login/', TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path('login/refresh/', TokenRefreshView.as_view(), name="token_refresh"),
    path('v1/', include(router.urls)),
    path('v1/', router.APIRootView.as_view(), name="v1"),
]

bloodeal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from accounts.views import sentry_error, generate_pdf

favicon_view = RedirectView.as_view(url='/static/img/favicon.png',
                                    permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('', include("accounts.urls"), name="accounts"),
    path('profiles/', include("profiles.urls"), name="profiles"),
    path('blurays/', include("blurays.urls"), name="blurays"),
    path('deals/', include("deals.urls"), name="deals"),
    path('movies/', include("movies.urls"), name="movies"),
    path('people/', include("people.urls"), name="people"),
    path('requests/', include("user_requests.urls"), name="user_requests"),
    path('api/', include("api.urls"), name="api"),
    path('site-admin/', admin.site.urls),
    path('sentry-debug/', sentry_error, name="sentry"),
    path('pdf/', generate_pdf, name="pdf"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blurays/urls.py
from django.urls import path

from blurays.views import BluRayListView, BluRayDetailView

# Création d'un espace de noms
app_name = 'blurays'

urlpatterns = [path('list/', BluRayListView.as_view(), name="blurays_list"),
               path('<str:slug>/<int:pk>/', BluRayDetailView.as_view(), name="blurays_detail")]

deals/urls.py
from django.urls import path

from deals.views import DealListView, DealCreateView, DealDetailView

# Création d'un espace de noms
app_name = "deals"

urlpatterns = [path("list/", DealListView.as_view(), name="deals_list"),
               path("<int:pk>/", DealDetailView.as_view(), name="deals_detail"),
               path("create/", DealCreateView.as_view(), name="deals_create")]

movies/urls.py
from django.urls import path

from movies.views import MovieListView, MovieDetailView


# Création d'un espace de noms
app_name = 'movies'

urlpatterns = [path("list/", MovieListView.as_view(), name="movies_list"),
               path("<str:slug>/<int:pk>/", MovieDetailView.as_view(), name="movies_detail")]

templates/403_csrf.html
{% extends "base.html" %}
{% load static %}

{% block left-block %}
{% endblock %}

{% block content %}
{% if modal %}
    {% include modal %}
{% endif %}
<section class="dashboard-block main-block-min-width justify-content-center">
    <h1 class="text-align-center">BL💿💿DEAL</h1>
    <div class="dashboard-block-element min-height-30vh justify-content-center">
        <div class="dashboard-block-element-title flex-column">
            <p class="signup-confirmation margin-1rem"><h2>Désolé, nous n'avons pas pu vous identifier.</h2></p>
            <p class="signup-confirmation margin-1rem"><h2>Merci de rafraîchir la page.</h2></p>
        </div>
        <div class="dashboard-block-element-content flex-wrap justify-content-center">
            <a href="{% url 'accounts:index' %}">
                <button class="btn btn-submit ">Revenir à l'accueil</button>
            </a>
        </div>
    </div>
</section>
{% endblock %}

{% block right-block %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js" defer></script>

    {% block title %}
    <title>Bloodeal</title>
    {% endblock %}

</head>

<body>

{% block header %}
    {% include "header.html" %}
{% endblock %}

    <main>
        <div class="dashboard-wrapper">

            {% block left-block %}
            <section class="dashboard-block side-block-min-width">
                <div class="dashboard-block-element min-height-20vh"></div>
                <div class="dashboard-block-element min-height-20vh"></div>
                <div class="dashboard-block-element min-height-20vh"></div>
                <div class="dashboard-block-element min-height-20vh"></div>
            </section>
            {% endblock %}

            {% block content %}
            <section class="dashboard-block main-block-min-width">
                <div class="dashboard-block-element min-height-30vh"></div>
                <div class="dashboard-block-element min-height-30vh"></div>
                <div class="dashboard-block-element min-height-30vh"></div>
                <div class="dashboard-block-element min-height-30vh"></div>
            </section>
            {% endblock %}

            {% block right-block %}
            <section class="dashboard-block side-block-min-width">
                <div class="dashboard-block-element min-height-20vh"></div>
                <div class="dashboard-block-element min-height-20vh"></div>
                <div class="dashboard-block-element min-height-20vh"></div>
                <div class="dashboard-block-element min-height-20vh"></div>
            </section>
            {% endblock %}

        </div>
    </main>

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

</body>

</html>

templates/footer.html
{% load static %}

<footer>
    <ul>
        <li><a href="{% url 'accounts:index' %}">&copy; {% now "Y" %} BLOODEAL</a></li>
        <li><a href="{% url 'accounts:help' %}">AIDE</a></li>
        <li><a href="{% url 'accounts:contact' %}">CONTACT</a></li>
        <li><a href="{% url 'api:v1' %}">API (DRF)</a></li>
    </ul>
    <button onclick="backToTopFunction()" id="backToTop" title="Go back to top">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 38 38">
    <path d="m 4 30 l 16 -20 l 16 20" />
    </svg>
    </button>
</footer>

templates/header.html
{% load static %}

<header>
    <nav class="nav-nav">
        <div class="nav-burger-and-searchbar">
            <span class="nav-title"><a href="{% url 'accounts:index' %}">BL💿💿DEAL</a></span>
            <div class="nav-burger" id="nav-burger">
                <div class="nav-burger-line"></div>
                <div class="nav-burger-line"></div>
                <div class="nav-burger-line"></div>
            </div>
            <span class="nav-home">
                <a href="{% url 'accounts:index' %}">
                    <img src="{% static 'img/logo-home.png' %}" alt="Home Logo - Freepik.com">
                </a>
            </span>
            <form class="nav-search-wrapper" action="{% url 'accounts:search_results' %}" method="GET">
                <input class="nav-search-bar" type="search" name="Q" placeholder="Tapez un mot-clé">
                    <button>
                       <svg width="44px" height="44px" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <g class="search-icon">
                            <path class="search" d="M10.0833 17.4167C14.1334 17.4167 17.4167 14.1334 17.4167 10.0833C17.4167 6.03325 14.1334 2.75 10.0833 2.75C6.03325 2.75 2.75 6.03325 2.75 10.0833C2.75 14.1334 6.03325 17.4167 10.0833 17.4167Z"/>
                            <path class="search" d="M19.25 19.25L15.2625 15.2625"/>
                          </g>
                        </svg>
                  </button>
            </form>
        </div>
<!--        <div class="nav-burger" id="nav-burger">-->
<!--            <div class="nav-burger-line"></div>-->
<!--            <div class="nav-burger-line"></div>-->
<!--            <div class="nav-burger-line"></div>-->
<!--        </div>-->
        <ul class="nav-ul" id="nav-ul">
            {% if not request.user.is_authenticated %}
            <li class="nav-li">
                    <a style="color: black; font-weight: 600;" href="{% url 'accounts:authenticate' %}">INSCRIPTION / CONNEXION</a>
            </li>
            {% endif %}
            <li class="nav-li"><a href="{% url 'deals:deals_list' %}">BONS PLANS</a></li>
            <li class="nav-li"><a href="{% url 'blurays:blurays_list' %}">BLU-RAYS</a></li>
            <li class="nav-li"><a href="{% url 'movies:movies_list' %}">FILMS</a></li>
            {% if request.user.is_authenticated %}
                <li class="nav-li"><a href="{% url 'profiles:favorites_list' %}">FAVORIS</a></li>
                <li class="nav-li" style="position: relative;"><a href="{% url 'user_requests:user_requests' pk=request.user.pk %}?filter=1+2+3+4">VOS DEMANDES</a>
                {% if user_requests_total %}<span class="notification">{{ user_requests_total }}</span>{% endif %}</li>
                <li class="nav-li"><a href="{% url 'profiles:profile_update' %}">PROFIL</a></li>
                <li class="nav-li"><a href="{% url 'accounts:logout' %}">SE DECONNECTER</a></li>
            {% endif %}

        </ul>
    </nav>
</header>

templates/modal.html
{% block modal %}
    <div class="modal" id="modal" aria-hidden="true" role="dialog">
        <div class="modal-content" id="modal-content">
            <svg width="24px" height="24px" viewBox="-4 -4 84 84" version="1.1" xmlns="http://www.w3.org/2000/svg" id="close-modal">
               <path d="M0,0 L77,77" id="Line"></path>
               <path d="M77,0 L0,77" id="Line"></path>
            </svg>
            <section>
                {% for message in modal_content %}
                    <h2>{{ message }}</h2>
                {% endfor %}
            </section>
        </div>
    </div>
{% endblock %}